/**
 * Defines constants for all metapointers in the "logo" language.
 * Generated by Freon LionWeb M3 generator
 */
export const Node = { language: "LionCore-builtins", key: "LionCore-builtins-Node", version: "1" }
export const INamed = { language: "LionCore-builtins", key: "LionCore-builtins-INamed", version: "1" }
export const Program = { language: "-key-LogoProgram", key: "-key-Program", version: "1" }
export const Library = { language: "-key-LogoProgram", key: "-key-Library", version: "1" }
export const ICommand = { language: "-key-LogoProgram", key: "-key-ICommand", version: "1" }
export const Forward = { language: "-key-LogoProgram", key: "-key-Forward", version: "1" }
export const Backward = { language: "-key-LogoProgram", key: "-key-Backward", version: "1" }
export const Left = { language: "-key-LogoProgram", key: "-key-Left", version: "1" }
export const Right = { language: "-key-LogoProgram", key: "-key-Right", version: "1" }
export const Heading = { language: "-key-LogoProgram", key: "-key-Heading", version: "1" }
export const MoveCommand = { language: "-key-LogoProgram", key: "-key-MoveCommand", version: "1" }
export const PenDown = { language: "-key-LogoProgram", key: "-key-PenDown", version: "1" }
export const PenUp = { language: "-key-LogoProgram", key: "-key-PenUp", version: "1" }
export const List = { language: "-key-LogoProgram", key: "-key-List", version: "1" }
export const SetPos = { language: "-key-LogoProgram", key: "-key-SetPos", version: "1" }
export const SetHeading = { language: "-key-LogoProgram", key: "-key-SetHeading", version: "1" }
export const HomeCommand = { language: "-key-LogoProgram", key: "-key-HomeCommand", version: "1" }
export const Repeat = { language: "-key-LogoProgram", key: "-key-Repeat", version: "1" }
export const If = { language: "-key-LogoProgram", key: "-key-If", version: "1" }
export const IExpression = { language: "-key-LogoProgram", key: "-key-IExpression", version: "1" }
export const Procedure = { language: "-key-LogoProgram", key: "-key-Procedure", version: "1" }
export const Parameter = { language: "-key-LogoProgram", key: "-key-Parameter", version: "1" }
export const ProcedureCall = { language: "-key-LogoProgram", key: "-key-ProcedureCall", version: "1" }
export const NumbericLiteral = { language: "-key-LogoProgram", key: "-key-NumbericLiteral", version: "1" }
export const GreaterThan = { language: "-key-LogoProgram", key: "-key-GreaterThan", version: "1" }

export const CLASSIFIER = {
    Node,
    INamed,
    Program,
    Library,
    ICommand,
    Forward,
    Backward,
    Left,
    Right,
    Heading,
    MoveCommand,
    PenDown,
    PenUp,
    List,
    SetPos,
    SetHeading,
    HomeCommand,
    Repeat,
    If,
    IExpression,
    Procedure,
    Parameter,
    ProcedureCall,
    NumbericLiteral,
    GreaterThan,
}
export const INamedName = { language: "LionCore-builtins", key: "LionCore-builtins-INamed-name", version: "2023.1" }
export const HeadingDegrees = { language: "-key-LogoProgram", key: "-key-Heading-degrees", version: "1" }
export const MoveCommandDistance = { language: "-key-LogoProgram", key: "-key-MoveCommand-distance", version: "1" }
export const SetPosX = { language: "-key-LogoProgram", key: "-key-SetPos-x", version: "1" }
export const SetPosY = { language: "-key-LogoProgram", key: "-key-SetPos-y", version: "1" }
export const SetHeadingDegrees = { language: "-key-LogoProgram", key: "-key-SetHeading-degrees", version: "1" }
export const RepeatCount = { language: "-key-LogoProgram", key: "-key-Repeat-count", version: "1" }
export const NumbericLiteralValue = { language: "-key-LogoProgram", key: "-key-NumbericLiteral-value", version: "1" }

export const PROPERTY = {
    INamedName,
    HeadingDegrees,
    MoveCommandDistance,
    SetPosX,
    SetPosY,
    SetHeadingDegrees,
    RepeatCount,
    NumbericLiteralValue,
}
export const ProcedureCallProcedure = { language: "-key-LogoProgram", key: "-key-ProcedureCall-procedure", version: "1" }

export const REFERENCE = {
    ProcedureCallProcedure,
}
export const ProgramCommands = { language: "-key-LogoProgram", key: "-key-Program-commands", version: "1" }
export const LibraryProcedures = { language: "-key-LogoProgram", key: "-key-Library-procedures", version: "1" }
export const ListCommands = { language: "-key-LogoProgram", key: "-key-List-commands", version: "1" }
export const RepeatList = { language: "-key-LogoProgram", key: "-key-Repeat-list", version: "1" }
export const IfCondition = { language: "-key-LogoProgram", key: "-key-If-condition", version: "1" }
export const IfIfTrue = { language: "-key-LogoProgram", key: "-key-If-ifTrue", version: "1" }
export const IfIfFalse = { language: "-key-LogoProgram", key: "-key-If-ifFalse", version: "1" }
export const ProcedureBody = { language: "-key-LogoProgram", key: "-key-Procedure-body", version: "1" }
export const ProcedureParameter = { language: "-key-LogoProgram", key: "-key-Procedure-parameter", version: "1" }
export const GreaterThanLeft = { language: "-key-LogoProgram", key: "-key-GreaterThan-left", version: "1" }
export const GreaterThanRight = { language: "-key-LogoProgram", key: "-key-GreaterThan-right", version: "1" }

export const CONTAINMENT = {
    ProgramCommands,
    LibraryProcedures,
    ListCommands,
    RepeatList,
    IfCondition,
    IfIfTrue,
    IfIfFalse,
    ProcedureBody,
    ProcedureParameter,
    GreaterThanLeft,
    GreaterThanRight,
}
