import { LionWebId, LionWebJsonMetaPointer, LionWebJsonReferenceTarget, LionWebJsonReference, LionWebJsonContainment, LionWebJsonProperty } from "@lionweb/server-delta-shared"
import { CONTAINMENT, GreaterThan, If, NumbericLiteral, Program, PROPERTY, REFERENCE } from "./keys.js"
import { LionWebJsonNode } from "@lionweb/json"

/**
 * Type definition for a LionWeb tree with embedded children.
 * Uses the names of the containments, properties and references as property names,
 * avoiding the unreadable LionWeb syntax.
 * By using the definitions of the containments, properties and references as generic
 * parameters, the tree can provide code completion and typechecking during editing.
 * 
 * NOTE: There is no knowledge of specific languages, so each feature may occurr inside each node.
 * 
 * Assumed usage: in tests.
 *
 * @see The `keys.ts` file as generated by the LionCore M3 Freon editor is needed
 *      for the definitions of the properties, containments and references.
 */
export type LionWebTree<T_PROP, T_CON, T_REF> = {
    [key in keyof T_CON]?: LionWebTree<T_PROP, T_CON, T_REF>[] | LionWebTree<T_PROP, T_CON, T_REF>
} & {
    [key in keyof T_PROP]?: string
} & {
    [key in keyof T_REF]?: LionWebJsonReferenceTarget[] | LionWebJsonReferenceTarget
} & {
    type: LionWebJsonMetaPointer
    id: LionWebId
    annotations?: LionWebTree<T_PROP, T_CON, T_REF>[]
}
const exp: LionWebTree<typeof PROPERTY, typeof CONTAINMENT, typeof REFERENCE> = {
    id: "id",
    type: If,
    GreaterThanLeft: [],
    IfCondition: [
        {
            type: GreaterThan,
            id: "id-gt",
            GreaterThanLeft: [
                {
                    type: NumbericLiteral,
                    id: "id-gtl",
                    NumbericLiteralValue: "12"
                }
            ],
            GreaterThanRight: [
                {
                    type: NumbericLiteral,
                    id: "id-gtr",
                    NumbericLiteralValue: "28"
                }
            ]
        }
        
    ]
}

/**
 * This class can convert a LionWebTree model to a collection of LionWeb nodes.  
 */
export class LionWebTreeConverter<P, C, R> {

    private nodes: LionWebJsonNode[] = []
    
    getConvertedNodes(): LionWebJsonNode[] {
        return this.nodes
    }
    
    convert(tree: LionWebTree<P, C, R>): void  {
        this.nodes = []
        this.treeToNode(tree)
    }
    /**
     * Create the LionWebJson node for the top node of the `tree` and traverse the full tree and convert it
     * to LionWebJson nodes and put those into `nodes.
     * @param tree
     */
    private treeToNode(tree: LionWebTree<P, C, R>): LionWebJsonNode {
        const node: LionWebJsonNode = {
            id: tree.id,
            classifier: tree.type,
            containments: [],
            properties: [],
            references: [],
            annotations: [],
            parent: null,
        }
        // find properties, containments, ...
        Object.keys(tree).forEach((key) => {
            if (key === "id" || key === "type") {
                return
            }
            const containmentMP = this.getContainment(key)
            if (containmentMP !== undefined) {
                const newContainment: LionWebJsonContainment = {
                    containment: containmentMP,
                    children: [],
                };

                // @ts-ignore
                (tree[key] as LionWebTree[]).forEach((childNode) => {
                    const child = this.treeToNode(childNode)
                    if (child !== null) {
                        child.parent = node.id
                        newContainment.children.push(child.id)
                    }
                })
                node.containments.push(newContainment)
                return
            }
            const propertyMP = this.getProperty(key)
            if (propertyMP !== undefined) {
                const newProperty: LionWebJsonProperty = {
                    property: propertyMP,
                    // @ts-ignore
                    value: tree[key] as string,
                }
                node.properties.push(newProperty)
                return
            }
            const referenceMP = this.getReference(key)
            if (referenceMP !== undefined) {
                const newReference: LionWebJsonReference = {
                    reference: referenceMP,
                    targets: []
                };

                // @ts-ignore
                (tree[key] as LionWebJsonReferenceTarget[]).forEach(refTarget => {
                    newReference.targets.push({ resolveInfo: "", reference: "" })
                })
                node.references.push(newReference)
                return
            }
            if (key === "annotations") {
                tree.annotations.forEach(ann => {
                    const annotationNode = this.treeToNode(ann)
                    annotationNode.parent = node.id
                    node.annotations.push(ann.id)
                })
                return
            }
            console.log(`Nothing found: ${key}`)
            throw new Error(`Nothing found: ${key}`)
        })
        this.nodes.push(node)
        return node
    }

    getContainment(name: string): LionWebJsonMetaPointer | undefined {
        for (const cont of Object.keys(CONTAINMENT)) {
            if (name === cont) {
                // @ts-ignore
                const CLS = CONTAINMENT[cont]
                // console.log(`Found ${name} in containments: ${JSON.stringify(CLS)}`)
                return CLS
            }
        }
        return undefined
    }
    getReference(name: string): LionWebJsonMetaPointer | undefined {
        for (const cont of Object.keys(REFERENCE)) {
            if (name === cont) {
                // @ts-ignore
                const CLS = REFERENCE[cont]
                // console.log(`Found ${name} in references: ${JSON.stringify(CLS)}`)
                return CLS
            }
        }
        return undefined
    }
    getProperty(name: string): LionWebJsonMetaPointer | undefined {
        for (const cont of Object.keys(PROPERTY)) {
            if (name === cont) {
                // @ts-ignore
                const CLS = PROPERTY[cont]
                // console.log(`Found ${name} in properties: ${JSON.stringify(CLS)}`)
                return CLS
            }
        }
        return undefined
    }
}
