import { LionWebId, LionWebJsonMetaPointer, LionWebJsonReferenceTarget, LionWebJsonReference, LionWebJsonContainment, LionWebJsonProperty } from "@lionweb/server-delta-shared"
import { CONTAINMENT, PROPERTY, REFERENCE } from "./keys.js"
import { LionWebJsonNode } from "@lionweb/json"

/**
 * Type definition for a tree with embedded children.
 * Uses the names of the containments, properties and references as property names,
 * avoiding the unreadable LionWeb syntax.
 * Assumed usage in tests.
 *
 * @see The `keys.ts` file as generated by the LionCore M3 Freon editor is needed.
 */
export type LionWebTree = {
    [key in keyof typeof CONTAINMENT]?: LionWebTree[] | LionWebTree
} & {
    [key in keyof typeof PROPERTY]?: string
} & {
    [key in keyof typeof REFERENCE]?: LionWebJsonReferenceTarget[] | LionWebJsonReferenceTarget
} & {
    type: LionWebJsonMetaPointer
    id: LionWebId
    annotations?: LionWebTree[]
}

/**
 * This class can convert a LionWeb model tree to a collection of LionWeb nodes.  
 */
export class LionWebTreeConverter {

    private nodes: LionWebJsonNode[] = []
    
    getConvertedNodes(): LionWebJsonNode[] {
        return this.nodes
    }
    
    convert(tree: LionWebTree): void  {
        this.nodes = []
        this.treeToNode(tree)
    }
    /**
     * Create the LionWebJson node for the top node of the `tree` and traverse the full tree and convert it
     * to LionWebJson nodes and put those into `nodes.
     * @param tree
     */
    private treeToNode(tree: LionWebTree): LionWebJsonNode {
        const node: LionWebJsonNode = {
            id: tree.id,
            classifier: tree.type,
            containments: [],
            properties: [],
            references: [],
            annotations: [],
            parent: null,
        }
        // find properties, containments, ...
        Object.keys(tree).forEach((key) => {
            if (key === "id" || key === "type") {
                return
            }
            const containmentMP = this.getContainment(key)
            if (containmentMP !== undefined) {
                console.log(`Found containment ${key}`)
                const newContainment: LionWebJsonContainment = {
                    containment: containmentMP,
                    children: [],
                }

                // @ts-ignore
                ;(tree[key] as LionWebTree[]).forEach((childNode) => {
                    const child = this.treeToNode(childNode)
                    if (child !== null) {
                        child.parent = node.id
                        newContainment.children.push(child.id)
                    }
                })
                node.containments.push(newContainment)
                return
            }
            const propertyMP = this.getProperty(key)
            if (propertyMP !== undefined) {
                console.log(`Found property ${key}`)
                const newProperty: LionWebJsonProperty = {
                    property: propertyMP,
                    // @ts-ignore
                    value: tree[key] as string,
                }
                node.properties.push(newProperty)
                return
            }
            const referenceMP = this.getReference(key)
            if (referenceMP !== undefined) {
                console.log(`Found reference ${key}`)
                const newReference: LionWebJsonReference = {
                    reference: referenceMP,
                    targets: []
                }

                // @ts-ignore
                ;(tree[key] as LionWebJsonReferenceTarget[]).forEach(refTarget => {
                    newReference.targets.push({ resolveInfo: "", reference: "" })
                })
                node.references.push(newReference)
                return
            }
            console.log(`Nothing found: ${key}`)
            throw new Error(`Nothing found: ${key}`)
        })
        this.nodes.push(node)
        return node
    }

    getContainment(name: string): LionWebJsonMetaPointer | undefined {
        for (const cont of Object.keys(CONTAINMENT)) {
            if (name === cont) {
                // @ts-ignore
                const CLS = CONTAINMENT[cont]
                console.log(`Found ${name} in containments: ${JSON.stringify(CLS)}`)
                return CLS
            }
        }
        return undefined
    }
    getReference(name: string): LionWebJsonMetaPointer | undefined {
        for (const cont of Object.keys(REFERENCE)) {
            if (name === cont) {
                // @ts-ignore
                const CLS = REFERENCE[cont]
                console.log(`Found ${name} in references: ${JSON.stringify(CLS)}`)
                return CLS
            }
        }
        return undefined
    }
    getProperty(name: string): LionWebJsonMetaPointer | undefined {
        for (const cont of Object.keys(PROPERTY)) {
            if (name === cont) {
                // @ts-ignore
                const CLS = PROPERTY[cont]
                console.log(`Found ${name} in properties: ${JSON.stringify(CLS)}`)
                return CLS
            }
        }
        return undefined
    }
}
