name: Build and publish docker image on new tag creation
on:
  push:
    tags:
      - '@lionweb/server@*'

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  # Label of the build job
  build:
    # Containers must run in Linux based operating systems
    runs-on: ubuntu-24.04
    # Docker Hub image that `container-job` executes in
    container: node:24.4.1
    steps:
      - name: install node
        uses: actions/setup-node@v7
        with:
          node-version: 24

      - name: Checkout
        uses: actions/checkout@v7

      - name: Install dependencies
        run: npm install

      - name: Remove @lionweb/server link
        run: rm -rf node_modules/@lionweb/server

      - name: setup
        run: npm run setup

      - name: tsc
        run: npm run build

# Only upload packages needed to run the server, exclude client packages
      - name: Upload dist
        uses: actions/upload-artifact@v7
        with:
          name: dist
          path: |
            packages/shared/dist/
            packages/server-logging/dist/
            packages/delta-shared/dist/
            packages/server-delta-definitions/dist/
            packages/database/dist/
            packages/dbadmin/dist/
            packages/history/dist/
            packages/delta-server/dist/
            packages/additionalapi/dist/
            packages/bulkapi/dist/
            packages/common/dist/
            packages/inspection/dist/
            packages/languages/dist/
            packages/server/dist/
          if-no-files-found: error
          overwrite: true

# Uplocad the node_modules that is filled by npm install
# TODO: get rid of all the dev packages, like typescript, prettier, etc.
      - name: Upload node modules
        uses: actions/upload-artifact@v7
        with:
          name: node_modules
          path: |
            node_modules
          if-no-files-found: error
          overwrite: true

  docker:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v7

# Download all the files that were uploaded by the build job and merge the dist folders
      - name: Download dist
        uses: actions/download-artifact@v7
        with:
          name: dist
          path: packages
          merge-multiple: true

# Download the uploaded node_modules
      - name: Download node_modules
        uses: actions/download-artifact@v7
        with:
          name: node_modules
          path: node_modules
          merge-multiple: true

      - name: Log into the Container registry
        uses: docker/login-action@v4
        with:          
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata for the Docker image
        id: meta
        uses: docker/metadata-action@v6
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          flavor: |
            latest=true
            prefix=release,onlatest=false
            suffix=,onlatest=false
          tags: |
            type=semver,pattern={{version}}
            type=ref,event=tag
      - name: Echo
        run: |
          echo "Tags [${{steps.meta.outputs.tags}}]"
          echo "env.REGISTRY [${{env.REGISTRY}}]"
          echo "env.IMAGE_NAME [${{env.IMAGE_NAME}}]"

      - name: Build and push the Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
